### ISSUE TITLE
'PCreateCommand' object has no attribute 'simulate'

### ISSUE THREAD

**Issue by btbytes** [sixfeetup/sixieskel.pyramid#5]
```
tmp  pcreate -t sfu_pyramid_basic spb
Creating directory /Users/pradeep/tmp/spb
Traceback (most recent call last):
  File "/Users/pradeep/.virtualenvs/py27/bin/pcreate", line 8, in <module>
    load_entry_point('pyramid==1.4', 'console_scripts', 'pcreate')()
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/pyramid-1.4-py2.7.egg/pyramid/scripts/pcreate.py", line 16, in main
    return command.run()
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/pyramid-1.4-py2.7.egg/pyramid/scripts/pcreate.py", line 75, in run
    return self.render_scaffolds()
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/pyramid-1.4-py2.7.egg/pyramid/scripts/pcreate.py", line 93, in render_scaffolds
    scaffold.run(self, output_dir, vars)
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/templer.core-1.0b4-py2.7.egg/templer/core/base.py", line 127, in run
    templates.Template.run(self, command, output_dir, vars)
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/paste/script/templates.py", line 58, in run
    self.write_files(command, output_dir, vars)
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/templer.core-1.0b4-py2.7.egg/templer/core/base.py", line 229, in write_files
    super(BaseTemplate, self).write_files(command, output_dir, vars)
  File "/Users/pradeep/.virtualenvs/py27/lib/python2.7/site-packages/paste/script/templates.py", line 115, in write_files
    if not command.simulate:
AttributeError: 'PCreateCommand' object has no attribute 'simulate'
```

**Comment by claytron** [comment]
@nrb any idea what is causing this?

**Comment by btbytes** [comment]
10th anniversary check... and closed ;)
